FROM node:18.17.1 as build
ARG CI=true
WORKDIR /usr/src/app
COPY . ./
ENV VITE_APP_ENV=$VITE_APP_ENV
RUN ["npm", "i"]
RUN ["npm", "run", "build"]

# Stage - Production
FROM nginx:stable as runner
COPY --from=build /usr/src/app/dist /usr/share/nginx/html/
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
