FROM node:14.6.0 as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . ./
RUN ["npm", "run", "build"]

# Stage - Production
FROM nginx:stable as runner
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
