FROM node:14.6.0 as build
ARG REACT_APP_ENV=test
WORKDIR /usr/src/app
COPY . ./
ENV REACT_APP_ENV=$REACT_APP_ENV
RUN ["npm", "run", "build"]

# Stage - Production
FROM nginx:stable as runner
COPY --from=build /usr/src/app/build /usr/share/nginx/html/
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
