name: build-other-branches

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build_other_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.6.0'

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run test:all
  
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build and push compose
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: provenanceio/explorer-frontend-${{ steps.get-branch-name.outputs.branch }}:latest
  
  
  