name: build-mainnet

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-mainnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v1
        with:
          node-version: "18.17.1"

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push mainnet
        uses: docker/build-push-action@v2
        with:
          target: runner
          file: Dockerfile-prod
          context: .
          push: true
          tags: provenanceio/explorer-frontend:${{ github.ref_name }}
          build-args: VITE_APP_ENV=production
